# ---------------- #
#   Main Configs   #
# ---------------- #
title: Zlbb - Zale and Libe Blog 张乐和李贝贝的博客 张乐和李贝贝二人网站
name: Zlbb
description: Zale and Libe Blog 张乐和李贝贝的博客 张乐和李贝贝二人网站
keywords: Zale, Libe, 张乐, 李贝贝, blog, 博客, 二人网站

url:
baseurl:  "/"
domain:   "zlbb.pub"
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/zlbb/zlbb.github.io

timezone: Asia/Shanghai
encoding: "utf-8"

# ---------------- #
#      Author      #
# ---------------- #
organization: Institute of Computing Technology Chinese Academy of Sciences
organization_url: http://www.ict.ac.cn/
location: Beijing, China
email: 810881283@qq.com
github_account: zl810881283
resumes:
  -
    lang: 中文简历
    link: /attachments/resumes/zhangle_resume_cn.pdf
    icon: cn
  -
    lang: English CV
    link:
    icon: gb
# ---------------- #
#      Jekyll      #
# ---------------- #
markdown:    kramdown
kramdown:
  input: GFM

highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

exclude: ["node_modules", "bower.json", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json"]
source:      .
destination: ./_site

quiet:    false
defaults: []

gems:
  - jemoji
  - rouge
  - jekyll-html-pipeline
  - jekyll-paginate

# ---------------- #
#    Analytics     #
# ---------------- #
# support provider: google, baidu
# !!!Important!!! Please modify tracking_id below to yours
analytics:
  provider: google
  google:
    tracking_id: 'UA-76860417-1'
  baidu:
    tracking_id: 'f0c036c8faf0eda95f1daedde0f0a398'

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

#  -
#    href: /blog
#    label: Blog

  -
    href: /categories
    label: Categories

  -
    href: /wiki
    label: Wiki

  -
    href: /bookmark
    label: Bookmark

  -
    href: /open-source
    label: Open-source

  -
    href: /about
    label: About

# ---------------- #
#       Wiki       #
# ---------------- #
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Socials     #
# ---------------- #
socials:
  -
    type: ZhiHu
    account: zl810881283
    home: https://www.zhihu.com/people/zl810881283
  -
    type: Twitter
    account:
  -
    type: Facebook
    account:

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
# !!!Important!!! Please modify usernames below to yours
comments:
  provider: disqus
  disqus:
    username: zl810881283
    sitename: zale
  duoshuo:
    username:
    sitename:
  changyan:
    appid:
    conf:

# ---------------- #
#      Data        #
# ---------------- #
skill_software_keywords: [Java, C, C++, NodeJs, Python, MySQL, Oracle, SQLite, MongoDB, HBase, Hadoop, Spark, Design Patterns]
skill_j2ee_keywords: [Spring, SpringMVC, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, Javascript, Jquery, Bootstrap, Angular, Express, ThinkJs, ]
skill_mobile_app_keywords: [Android, Ionic, Cordova]
popular_repos: ['ppt', 'RandomName', 'Java-BackGammon', 'zl810881283.github.io', 'project_template']
contribute_repos: ['academic-zl/SEMAGE', 'outsourcingproject/auction', 'outsourcingproject/zhazha.com', 'outsourcingproject/wechart_shop']
personal_titles: [ 'Zale plans to be a Full Stack developer', 'Zale dreams to be a CTO', 'Zale is now study in Chongqing university', 'Zale loves coding and innovating', 'Zale has girlfriend now, so not available :D', 'Zale is so cool, right?']
